// <auto-generated />
namespace AnderoTest_461.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SavedDates_NorRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SavedDates_NorRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201808311358389_SavedDates_NorRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
